apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: njoroge0330/to-do-frontend
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: to-do-frontend-service
spec:
  type: NodePort 
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007  # Optional: Kubernetes will choose one if omitted (range: 30000–32767)

